SYNONYM_MAP = {
    "codigo de barras": "barcode",
    "linha digitavel": "barcode",
    "barcode": "barcode",
    "vencimento": "due_date",
    "data de vencimento": "due_date",
    "data vencimento": "due_date",
    "valor": "document_value",
    "valor do documento": "document_value",
    "valor total": "document_value",
    "total a pagar": "document_value",
    "cnpj": "payee_cnpj",
    "cnpj do cedente": "payee_cnpj",
    "cnpj cedente": "payee_cnpj",
    "cnpj do beneficiario": "payee_cnpj",
    "cnpj beneficiario": "payee_cnpj",
    "cnpj do emissor": "payee_cnpj",
    "cnpj emissor": "payee_cnpj",
    "cnpj do pagador": "payer_cnpj",
    "cnpj pagador": "payer_cnpj",
    "cnpj do sacado": "payer_cnpj",
    "cpf": "cpf",
    "juros": "juros",
    "multa": "multa",
    "endereco de cobranca": "payer_address",
    "local de cobranca": "payer_address",
    "endereco do pagador": "payer_address",
    "endereco do sacado": "payer_address",
    "endereco do cliente": "payer_address",
    "endereco do cedente": "payee_address",
    "endereco do beneficiario": "payee_address",
    "endereco do emissor": "payee_address",
    "nome do cedente": "payee_name",
    "nome do sacado": "payer_name",
    "nosso numero": "document_number",
    "numero do documento": "document_number",
    "numero da conta": "document_number",
    "instrucoes": "instructions",
}

TYPE_BY_BUILTIN = {
    "due_date": "date",
    "document_value": "money",
    "barcode": "barcode",
    "billing_address": "address",
    "payer_address": "address",
    "payee_address": "address",
    "cnpj": "cnpj",
    "payer_cnpj": "cnpj",
    "payee_cnpj": "cnpj",
    "cpf": "cpf",
    "payee_name": "text",
    "payer_name": "text",
    "document_number": "id",
    "instructions": "text",
    "juros": "money",
    "multa": "money",
}
